### ISSUE TITLE
enhancement -  docker/podman install?

### ISSUE THREAD

**Issue by c-nv-s** [cwbooth5/go2redirector#10]
not essential ( you can close this ticket ) but a Dockerfile might be a "nice to have" for this project.

**Comment by cwbooth5** [comment]
I agree, but for which purpose(s)? I can see a couple. 

One would be to just build the binary. 

The second would be to actually run it. I'm assuming you're talking about a single container that would build it, then run it with some sensible defaults to allow the user to cheick out the application?

A container is a great idea for packaging too. My intended use of this executable and its templates/static files was to run it plain HTTP behind nginx or some other proxy. Maybe we could write a simple container to fire up nginx to show how to set it up.

Thoughts?

**Comment by c-nv-s** [comment]
> 
> The second would be to actually run it. I'm assuming you're talking about a single container that would build it, then run it with some sensible defaults to allow the user to cheick out the application?
> 
This is more along the lines of what I was thinking.
I was stating it isn't essential because it might even be simpler for you to just release binaries with the help of something like [https://goreleaser.com](https://github.com/goreleaser/goreleaser)

**Comment by cwbooth5** [comment]
The container's a pretty easy option to just build it real quick and test it out, so I just checked in an example Dockerfile.

For release, I'd need to bundle all my static assets along with the binary. The container is a good option. The other one I can think of is a tarball, which I could create with goreleaser. I'll think about how I can/should distribute this.
